import { AlgorithmCode } from '@/types/algorithm';

export const nQueensCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function solveNQueens(n, maxSolutions = 1) {',
      '  const board = Array(n).fill(-1);',
      '  const solutions = [];',
      '  ',
      '  function isSafe(row, col) {',
      '    for (let i = 0; i < row; i++) {',
      '      const c = board[i];',
      '      if (c === col) return false;',
      '      if (Math.abs(c - col) === Math.abs(i - row))',
      '        return false;',
      '    }',
      '    return true;',
      '  }',
      '  ',
      '  function solve(row) {',
      '    if (row === n) {',
      '      solutions.push([...board]);',
      '      return solutions.length >= maxSolutions;',
      '    }',
      '    ',
      '    for (let col = 0; col < n; col++) {',
      '      if (isSafe(row, col)) {',
      '        board[row] = col;',
      '        if (solve(row + 1)) return true;',
      '        board[row] = -1; // backtrack',
      '      }',
      '    }',
      '    ',
      '    return false;',
      '  }',
      '  ',
      '  solve(0);',
      '  return solutions;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def solve_n_queens(n, max_solutions=1):',
      '    board = [-1] * n',
      '    solutions = []',
      '    ',
      '    def is_safe(row, col):',
      '        for i in range(row):',
      '            c = board[i]',
      '            if c == col:',
      '                return False',
      '            if abs(c - col) == abs(i - row):',
      '                return False',
      '        return True',
      '    ',
      '    def solve(row):',
      '        if row == n:',
      '            solutions.append(board[:])',
      '            return len(solutions) >= max_solutions',
      '        ',
      '        for col in range(n):',
      '            if is_safe(row, col):',
      '                board[row] = col',
      '                if solve(row + 1):',
      '                    return True',
      '                board[row] = -1  # backtrack',
      '        ',
      '        return False',
      '    ',
      '    solve(0)',
      '    return solutions',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'SOLVE-N-QUEENS(n, maxSolutions)',
      '  board = array of size n, all -1',
      '  solutions = []',
      '  ',
      '  IS-SAFE(row, col)',
      '    for i = 0 to row - 1',
      '      c = board[i]',
      '      if c = col then return false',
      '      if |c - col| = |i - row| return false',
      '    return true',
      '  ',
      '  SOLVE(row)',
      '    if row = n',
      '      add copy of board to solutions',
      '      return |solutions| ≥ maxSolutions',
      '    ',
      '    for col = 0 to n - 1',
      '      if IS-SAFE(row, col)',
      '        board[row] = col',
      '        if SOLVE(row + 1) return true',
      '        board[row] = -1  // backtrack',
      '    ',
      '    return false',
      '  ',
      '  SOLVE(0)',
      '  return solutions',
    ],
  },
};
