import { AlgorithmCode } from '@/types/algorithm';

export const fibonacciCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function fibonacci(n, strategy = "dp-array") {',
      '  // Base cases',
      '  if (n <= 1) return n;',
      '  ',
      '  if (strategy === "iterative") {',
      '    // Iterative O(1) space',
      '    let a = 0, b = 1;',
      '    for (let i = 2; i <= n; i++) {',
      '      const temp = a + b;',
      '      a = b;',
      '      b = temp;',
      '    }',
      '    return b;',
      '  }',
      '  ',
      '  if (strategy === "fast-doubling") {',
      '    // Fast doubling for very large n',
      '    function fastDoubling(k) {',
      '      if (k === 0) return [0n, 1];',
      '      if (k === 1) return [1n, 1];',
      '      ',
      '      const [a, b] = fastDoubling(Math.floor(k / 2));',
      '      const c = a * (2n * b - a);',
      '      const d = b * b + a * a;',
      '      ',
      '      return k % 2 === 0 ? [c, d] : [d, c + d];',
      '    }',
      '    return fastDoubling(n)[0];',
      '  }',
      '  ',
      '  // DP Array O(n) space',
      '  const dp = new Array(n + 1);',
      '  dp[0] = 0;',
      '  dp[1] = 1;',
      '  ',
      '  for (let i = 2; i <= n; i++) {',
      '    dp[i] = dp[i - 1] + dp[i - 2];',
      '  }',
      '  ',
      '  return dp[n];',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def fibonacci(n, strategy="dp-array"):',
      '    # Base cases',
      '    if n <= 1:',
      '        return n',
      '    ',
      '    if strategy == "iterative":',
      '        # Iterative O(1) space',
      '        a, b = 0, 1',
      '        for i in range(2, n + 1):',
      '            a, b = b, a + b',
      '        return b',
      '    ',
      '    if strategy == "fast-doubling":',
      '        # Fast doubling for very large n',
      '        def fast_doubling(k):',
      '            if k == 0:',
      '                return (0, 1)',
      '            if k == 1:',
      '                return (1, 1)',
      '            ',
      '            a, b = fast_doubling(k // 2)',
      '            c = a * (2 * b - a)',
      '            d = b * b + a * a',
      '            ',
      '            return (c, d) if k % 2 == 0 else (d, c + d)',
      '        ',
      '        return fast_doubling(n)[0]',
      '    ',
      '    # DP Array O(n) space',
      '    dp = [0] * (n + 1)',
      '    dp[0] = 0',
      '    dp[1] = 1',
      '    ',
      '    for i in range(2, n + 1):',
      '        dp[i] = dp[i - 1] + dp[i - 2]',
      '    ',
      '    return dp[n]',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'FIBONACCI(n, strategy)',
      '  if n ≤ 1',
      '    return n',
      '  ',
      '  if strategy = "iterative"',
      '    a ← 0, b ← 1',
      '    for i = 2 to n',
      '      temp ← a + b',
      '      a ← b',
      '      b ← temp',
      '    return b',
      '  ',
      '  if strategy = "fast-doubling"',
      '    return FAST-DOUBLING(n)',
      '  ',
      '  // DP Array strategy',
      '  dp = array of size n + 1',
      '  dp[0] ← 0',
      '  dp[1] ← 1',
      '  ',
      '  for i = 2 to n',
      '    dp[i] ← dp[i - 1] + dp[i - 2]',
      '  ',
      '  return dp[n]',
    ],
  },
};
